name: Developer workflow performance

env:
  NODE_LTS_VERSION: 20

on:
  workflow_dispatch:
  push:
    # branches: ['canary']

jobs:
  run:
    name: Run benchmarks
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.35.0-focal
    strategy:
      fail-fast: false
      matrix:
        mode:
          - '--turbopack=false'
          - '--turbopack=true'
        selector:
          - '--scenario=heavy-npm-deps --page=homepage'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
      - run: corepack enable

      - run: pnpm install

      - name: Run benchmarks
        run: node ./node_modules/.bin/devlow-bench --datadog=ubuntu-latest-16-core ${{ matrix.mode }} ${{ matrix.selector }}
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          BROWSER_OUTPUT: 1
          SHELL_OUTPUT: 1

      - run: echo "Benchmark completed"
